### ISSUE TITLE
Getting `Invalid Version: v0.1.8`

### ISSUE THREAD

**Issue by SorenHolstHansen** [superfaceai/release-changelog-action#262]
I found your blog post with your [npm publishing workflow](https://superface.ai/blog/npm-publish-gh-actions-changelog) and really liked it. However when I try and implement it for our package [openapi-zod](https://github.com/wayfare-ai/openapi-zod) I get an error in the [update changelog step](https://github.com/wayfare-ai/openapi-zod/actions/runs/3777721484/jobs/6421698101) `Error: invalid version v0.1.8`.

I have googled a bit, but was unable to find anything of help. Do you guys have any idea what the problem is?

**Comment by janhalama** [comment]
Hi, I do not have access to your package [openapi-zod](https://github.com/wayfare-ai/openapi-zod).

I recently released new major version v2 of this Github Action but did not update the article yet. It is backward compatible with v1 and can be replaced easily just by changing the version number. I recommend to use the latest major version. That is the only hint for now, I really need more details to be able to help.

```
# Update changelog unreleased section with new version
      - name: Update changelog
        uses: superfaceai/release-changelog-action@**v2**
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: release
```
