### ISSUE TITLE
Allow to use `markdownlint` format of `keep-a-changelog` version `2.2.0`

### ISSUE THREAD

**Issue by Ndpnt** [superfaceai/release-changelog-action#269]
Hi,

Thanks for this useful GitHub Action to generate changelog.

We need to generate a changelog that respect [markdownlint](https://github.com/DavidAnson/markdownlint) rules.
An update has been made on `keep-a-changelog` module in version `2.2.0` in this way. 
Could you allow to specify the output format as parameter of this GitHub action?

Something like this:
```
name: Get version changelog
  on:
    ...

  jobs:
    get-changelog:
      steps:
        - uses: actions/checkout@v2
        - name: Get changelog
          id: get-changelog
          uses: @superfaceai/release-changelog-action@v2
          with:
            path-to-changelog: CHANGELOG.md
            version: 1.0.0
            format: markdownlint
        - name: Log changelog
          run: echo ${{ steps.get-changelog.outputs.changelog }}
```
