### ISSUE TITLE
Example is wrong?

### ISSUE THREAD

**Issue by Syndesi** [superfaceai/release-changelog-action#307]
Hi,

the at sign in the action name of your examples seem to be wrong; with it there GitHub doesn't recognize the workflow file and without it your action works as expected:

```
jobs:
  release:
    steps:
      - uses: actions/checkout@v2
      - name: Update changelog
        uses: @superfaceai/release-changelog-action@v2
              ^ this at sign is problematic <--------------------------------------------------------
        with:
          path-to-changelog: CHANGELOG.md  # optional, default value is `CHANGELOG.md`
          version: 1.0.0
          operation: release
          format: markdownlint # optional, valid values are `compact` (default) or `markdownlint`
```
Other examples use this name as well.
